### ISSUE TITLE
not running

### ISSUE THREAD

**Issue by BodaTomato** [araekiel/instahunter#4]
Traceback (most recent call last):
  File "Desktop/tools/OSINT/social/instahunter/src/main.py", line 3, in <module>
    from lib.io import display_header, get_input, create_json_file, display_data, display_message
  File "/home/boda/Desktop/tools/OSINT/social/instahunter/src/lib/io.py", line 3, in <module>
    from PyInquirer import prompt
  File "/usr/local/lib/python3.10/dist-packages/PyInquirer-1.0.3-py3.10.egg/PyInquirer/__init__.py", line 6, in <module>
    from prompt_toolkit.token import Token
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/application.py", line 8, in <module>
    from .key_binding.bindings.basic import load_basic_bindings
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/key_binding/bindings/basic.py", line 9, in <module>
    from prompt_toolkit.renderer import HeightIsUnknownError
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/renderer.py", line 11, in <module>
    from prompt_toolkit.styles import Style
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/__init__.py", line 8, in <module>
    from .from_dict import *
  File "/usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/from_dict.py", line 9, in <module>
    from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by mrofcodyx** [comment]
resolved:

1) pip3 install --upgrade prompt_toolkit PyInquirer
2) nano /usr/local/lib/python3.10/dist-packages/prompt_toolkit/styles/from_dict.py
and replace: "from collections import Mapping" 
With: "from collections.abc import Mapping"

3) Save the file and try running your script again.
![image](https://github.com/user-attachments/assets/1aa8e962-5d1a-4aa5-a879-46d5691e2234)
